name: Check PR

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"

      - name: Clean install dependencies and build
        run: |
          npm ci
          npm run build
