name: Release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"

      - name: Clean install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Zip-up function app package
        run: |
          zip -r ./deployment/app.zip *

      - name: Zip-up build artifact
        run: zip -r build.zip ./deployment/ ./README.md

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - uses: actions/download-artifact@v2
        with:
          name: build

      - name: Generate release filename
        run: mv build.zip good-vibes-generator.zip

      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "good-vibes-generator.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
